### PR TITLE
Add faster DatapointRouter implementations

### PR DESCRIPTION
**Pull request by iksaif**
This change is [Reviewable](https://reviewable.io/reviews/criteo-forks/carbon/2)

### CODE REVIEW

**Comment by iksaif** [comment]
+@unbrice 

<details><summary>

<i>Previously, iksaif (Corentin Chary) wrote…</i></summary>



> #### Add faster DatapointRouter implementations
> 
> </details>

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-:-KHU4qrmIxAhUyfRApi-:-1491293608)_

**Comment by unbrice** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_[lib/carbon/routers.py, line 8 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW5uP3k1kYdTmMz1aL:-KHW5uP4c2_UEyRH0LRI:1678884275) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/routers.py#L8)):_

> ``` Python
> class DatapointRouter(object):
>   "Abstract base class for datapoint routing logic implementations"
>   __metaclass__ = PluginRegistrar
> ```

This code base is sick.

---

_[lib/carbon/routers.py, line 30 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW-IQAbQ64d0aQcgZm:-KHW-IQAbQ64d0aQcgZn:-2075312581) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/routers.py#L30)):_

> ``` Python
> 
>   def __init__(self, settings):
>     from carbon.relayrules import loadRelayRules
> ```

Why is this import not with the other? (please put it back or add a comment)

---

_[lib/carbon/routers.py, line 32 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW-ePRN_G4_-xZHoZE:-KHW-ePRN_G4_-xZHoZF:-50130629) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/routers.py#L32)):_

> ``` Python
>     from carbon.relayrules import loadRelayRules
> 
>     rules_path = settings['relay-rules']
> ```

This project seems to use double quotes.

---

_[lib/carbon/routers.py, line 167 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW1bAQ1DAJuuIZQ-mZ:-KHW1bAQ1DAJuuIZQ-m_:-586434851) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/routers.py#L167)):_

> ``` Python
>     Instead of trying to avoid rebalancing data when changing
>     the list of nodes we try to making routing as fast as we
>     can.
> ```

I suspect rendez-vous hashing would be about as fast and simple while retaining the advantage of avoiding rebalances. Unless we don't care _at all_ about rebalances (biggraphite?) in which case you should explicitate that as a design consideration.

---

_[lib/carbon/routers.py, line 178 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW02G-FSXh_vc3dfwN:-KHW02G0-ekEVLFDpVB2:-1289123438) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/routers.py#L178)):_

> ``` Python
> 
>     def _update_nodes(self):
>       self.sorted_nodes = sorted(list(self.nodes))
> ```

sorted is enough (no need to create a list)

---

_[lib/carbon/routers.py, line 189 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW2NKfTwTq7_JBRum6:-KHW2NKfTwTq7_JBRum7:-1663688189) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/routers.py#L189)):_

> ``` Python
> 
>     def get_nodes(self, key):
>       end_index = index = self._hash(key) % len(self.nodes)
> ```

A for loop would make the control flow more readable. I suggest:

``` python
seed = self._hash(key)
for n in xrange(seed, seed+len(self.nodes)):
  yield self.sorted_nodes[n % len(self.sorted_nodes)]
```

or if the list of often consumed in its entirety:

``` python
split = self._hash(key)% len(self.sorted_nodes)
return self.sorted_nodes[split:] + self.sorted_nodes[:split]
```

---

_[lib/carbon/tests/relay-rules.conf, line 3 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW5POJHX1v0XNBRhoj:-KHW5POJHX1v0XNBRhok:1929076278) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/tests/relay-rules.conf#L3)):_

> ```
> [default]
> destinations = foo:124:a
> default = true
> ```

nit: missing line feed

---

_[lib/carbon/tests/test_routers.py, line 8 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW5dJVAOJypAU--lNT:-KHW5dJVAOJypAU--lNU:100710418) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/tests/test_routers.py#L8)):_

> ``` Python
> 
> 
> class FakeOptions(object):
> ```

There is already something like that in testutils I think

---

_[lib/carbon/tests/test_routers.py, line 47 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW5XoAkHfDgQa1C_Kc:-KHW5XoAkHfDgQa1C_Kd:-1161278611) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/tests/test_routers.py#L47)):_

> ``` Python
>         for destination in DESTINATIONS:
>             router.addDestination(parseDestination(destination))
>         self.assertEquals(len(list(router.getDestinations('foo.bar'))), 2)
> ```

instead of 2, what would you think of BASE_OPTIONS.REPLICATION_FACTOR

---

_[lib/carbon/tests/test_routers.py, line 54 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW5au0A24xh-LZEOqy:-KHW5au0A24xh-LZEOqz:-1161278611) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/tests/test_routers.py#L54)):_

> ``` Python
>         for destination in DESTINATIONS:
>             router.addDestination(parseDestination(destination))
>         self.assertEquals(len(list(router.getDestinations('foo.bar'))), 2)
> ```

instead of 2, what would you think of BASE_OPTIONS.REPLICATION_FACTOR

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/carbon/2)_

**Comment by unbrice** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_[lib/carbon/tests/test_routers.py, line 50 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW6_0Vblo0z19ljuH9:-KHW6_0WH2ny5-klMIuz:-1782008101) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/tests/test_routers.py#L50)):_

> ``` Python
> 
> class TestAggregatedConsistentHashingRouter(TestCase):
>     def testBasic(self):
> ```

testReplicationFactor?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/carbon/2)_

**Comment by iksaif** [comment]
Review status: 3 of 7 files reviewed at latest revision, 11 unresolved discussions.

---

_[lib/carbon/routers.py, line 8 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW5uP3k1kYdTmMz1aL:-KHWMU81V3Z4sO919j4Y:-499146009) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/routers.py#L8)):_
<details><summary>

<i>Previously, unbrice (Brice Arnould) wrote…</i></summary>



> This code base is sick.</details>
> Done.

---

_[lib/carbon/routers.py, line 30 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW-IQAbQ64d0aQcgZm:-KHWMjXpWgkKJsLWr_Ss:684491142) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/routers.py#L30)):_
<details><summary>

<i>Previously, unbrice (Brice Arnould) wrote…</i></summary>



> Why is this import not with the other? (please put it back or add a comment)</details>
> Added a comment. Basically carbon is full of circular dependencies.

---

_[lib/carbon/routers.py, line 32 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW-ePRN_G4_-xZHoZE:-KHWMviDx_mUlAnsJYv7:-499146009) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/routers.py#L32)):_
<details><summary>

<i>Previously, unbrice (Brice Arnould) wrote…</i></summary>



> This project seems to use double quotes.</details>
> Done.

---

_[lib/carbon/routers.py, line 167 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW1bAQ1DAJuuIZQ-mZ:-KHWN9Qi0jVoJB3SNZYM:-1254545593) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/routers.py#L167)):_
<details><summary>

<i>Previously, unbrice (Brice Arnould) wrote…</i></summary>



> I suspect rendez-vous hashing would be about as fast and simple while retaining the advantage of avoiding rebalances. Unless we don't care _at all_ about rebalances (biggraphite?) in which case you should explicitate that as a design consideration.</details>
> My guess is that it's good enough because carbonate does not know what has to be rebalanced and just rebalance everything.
> Also graphite-web does a pretty good job at merging data from multiple sources (before you rebalance)

Added comments.

---

_[lib/carbon/routers.py, line 178 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW02G-FSXh_vc3dfwN:-KHWNTlpR3JHgNESPqhU:-499146009) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/routers.py#L178)):_
<details><summary>

<i>Previously, unbrice (Brice Arnould) wrote…</i></summary>



> sorted is enough (no need to create a list)</details>
> Done.

---

_[lib/carbon/routers.py, line 189 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW2NKfTwTq7_JBRum6:-KHWOD-Rg9y6axcXCdzT:-499146009) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/routers.py#L189)):_
<details><summary>

<i>Previously, unbrice (Brice Arnould) wrote…</i></summary>



> A for loop would make the control flow more readable. I suggest:
> 
> ``` python
> seed = self._hash(key)
> for n in xrange(seed, seed+len(self.nodes)):
>   yield self.sorted_nodes[n % len(self.sorted_nodes)]
> ```
> 
> or if the list of often consumed in its entirety:
> 
> ``` python
> split = self._hash(key)% len(self.sorted_nodes)
> return self.sorted_nodes[split:] + self.sorted_nodes[:split]
> ```
> 
> </details>
> Done.

---

_[lib/carbon/tests/relay-rules.conf, line 3 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW5POJHX1v0XNBRhoj:-KHZv2QBJBGmeYkx_-o6:-499146009) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/tests/relay-rules.conf#L3)):_
<details><summary>

<i>Previously, unbrice (Brice Arnould) wrote…</i></summary>



> nit: missing line feed</details>
> Done.

---

_[lib/carbon/tests/test_routers.py, line 8 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW5dJVAOJypAU--lNT:-KHZv3-jJJEkSRotrO2g:-499146009) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/tests/test_routers.py#L8)):_
<details><summary>

<i>Previously, unbrice (Brice Arnould) wrote…</i></summary>



> There is already something like that in testutils I think</details>
> Done.

---

_[lib/carbon/tests/test_routers.py, line 47 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW5XoAkHfDgQa1C_Kc:-KHZyjHcR7IpQyBmKZT5:-499146009) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/tests/test_routers.py#L47)):_
<details><summary>

<i>Previously, unbrice (Brice Arnould) wrote…</i></summary>



> instead of 2, what would you think of BASE_OPTIONS.REPLICATION_FACTOR</details>
> Done.

---

_[lib/carbon/tests/test_routers.py, line 50 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW6_0Vblo0z19ljuH9:-KHZyjsFr1rfH9stpp1t:-576305686) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/tests/test_routers.py#L50)):_
<details><summary>

<i>Previously, unbrice (Brice Arnould) wrote…</i></summary>



> testReplicationFactor?</details>
> I changed some stuff here. But it really mostly tests that we can get some destinations, not a lot more.

---

_[lib/carbon/tests/test_routers.py, line 54 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW5au0A24xh-LZEOqy:-KHZyqJDgRrlKKWLV6xp:-499146009) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/tests/test_routers.py#L54)):_
<details><summary>

<i>Previously, unbrice (Brice Arnould) wrote…</i></summary>



> instead of 2, what would you think of BASE_OPTIONS.REPLICATION_FACTOR</details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/carbon/2)_

**Comment by unbrice** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHdHlPlPwTQ8nihQNa0:-KHdHlPlPwTQ8nihQNa1:-1868698381) (no related file):_
:lgtm_strong: 

---

_[lib/carbon/routers.py, line 30 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW-IQAbQ64d0aQcgZm:-KHdHH96nAKe6Xwb5HKo:-1937265778) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/routers.py#L30)):_
<details><summary>

<i>Previously, iksaif (Corentin Chary) wrote…</i></summary>



> Added a comment. Basically carbon is full of circular dependencies.</details>
> I suggest making this slightly more explicit than just a vague "dependency hell": what modules depend on this one that you depend on, or at least the error message you'd get.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/carbon/2)_

**Comment by iksaif** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

_[lib/carbon/routers.py, line 30 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHW-IQAbQ64d0aQcgZm:-KHdJRh28mM7b-tL0Bbh:-499146009) ([raw file](https://github.com/criteo-forks/carbon/blob/2558050048e14a648b274dfcfed9dbe2040025d5/lib/carbon/routers.py#L30)):_
<details><summary>

<i>Previously, unbrice (Brice Arnould) wrote…</i></summary>



> I suggest making this slightly more explicit than just a vague "dependency hell": what modules depend on this one that you depend on, or at least the error message you'd get.</details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/carbon/2)_

**Comment by unbrice** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/carbon/2)_

**Comment by unbrice** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHdHlPlPwTQ8nihQNa0:-KHdtiR-iHOSfyEiJrGb:-1868698381) (no related file):_
<details><summary>

<i>Previously, unbrice (Brice Arnould) wrote…</i></summary>



> :lgtm_strong: </details>
> :lgtm_strong: 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/carbon/2)_

**Comment by unbrice** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHduQT8RFrI4IzOqQB3:-KHduQT8RFrI4IzOqQB4:-1868698381) (no related file):_
:lgtm_strong: 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/carbon/2)_

**Comment by unbrice** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/criteo-forks/carbon/2#-KHdud03iU4jYZ4xjWdl:-KHdud03iU4jYZ4xjWdm:980077423) (no related file):_
:lgtm: 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/carbon/2)_

**Pull request merged**
