### PR TITLE
Enforce better syslog tag

### PR DESCRIPTION
**Pull request by sun77**
This change is [Reviewable](https://reviewable.io/reviews/criteo-forks/carbon/5)

### CODE REVIEW

**Comment by iksaif** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[lib/carbon/conf.py, line 265 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/5#-KK8GEfQAvDQ8PcPqIq-:-KK8GEfQAvDQ8PcPqIq0:-1112559383) ([raw file](https://github.com/criteo-forks/carbon/blob/6aaefd1eca89b90912aa9e21246d62ea5f4cf608/lib/carbon/conf.py#L265)):_

> ``` Python
>         if not self["debug"]:
>             if self.parent.get("syslog", None):
>                 prefix = "%s-%s[%d]" % (__builtin__.program, self["instance"], os.getpid())
> ```

maybe we can just use 'program' ?  (see program = self.parent.subCommand)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/carbon/5)_

**Comment by sun77** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[lib/carbon/conf.py, line 265 [r1]](https://reviewable.io:443/reviews/criteo-forks/carbon/5#-KK8GEfQAvDQ8PcPqIq-:-KK8InH2rwKjfPP3WmF4:-499146009) ([raw file](https://github.com/criteo-forks/carbon/blob/6aaefd1eca89b90912aa9e21246d62ea5f4cf608/lib/carbon/conf.py#L265)):_
<details><summary>

<i>Previously, iksaif (Corentin Chary) wrote…</i></summary>



> maybe we can just use 'program' ?  (see program = self.parent.subCommand)
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/carbon/5)_

**Comment by iksaif** [comment]
:lgtm:

<details><summary>

<i>Previously, sun77 (Anthony RABIER) wrote…</i></summary>



> #### Enforce better syslog tag
> 
> </details>

---

Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/carbon/5#-:-KK8WsK2EaLTDm0zweTz:1417088721)_

**Comment by unbrice** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[lib/carbon/conf.py, line 19 [r2]](https://reviewable.io:443/reviews/criteo-forks/carbon/5#-KK8XdDMYZUQvXkKFgkn:-KK8XdDNV4WwzDFlvx51:-2106457278) ([raw file](https://github.com/criteo-forks/carbon/blob/f15362d3d5719e2c984d9a784badffaf7be49a0e/lib/carbon/conf.py#L19)):_

> ``` Python
> import pwd
> import errno
> import __builtin__
> ```

Spurious import

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/carbon/5)_

**Comment by sun77** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[lib/carbon/conf.py, line 19 [r2]](https://reviewable.io:443/reviews/criteo-forks/carbon/5#-KK8XdDMYZUQvXkKFgkn:-KK8YCf5HOAMGGeii1sx:-499146009) ([raw file](https://github.com/criteo-forks/carbon/blob/f15362d3d5719e2c984d9a784badffaf7be49a0e/lib/carbon/conf.py#L19)):_
<details><summary>

<i>Previously, unbrice (Brice Arnould) wrote…</i></summary>



> Spurious import
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/carbon/5)_

**Comment by unbrice** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/criteo-forks/carbon/5)_

**Pull request merged**
